### PR TITLE
Added support for 64-bit

### PR DESCRIPTION
**Pull request by ludolphus**

### CODE REVIEW

**Comment by dezinezync** [comment]
@ludolphus Thanks Steven. could you please add the compiled files under the dist directory as well?

**Comment by ludolphus** [comment]
The zip for 1.2 is already in the PR under the dist directory.

**Comment by dezinezync** [comment]
My bad. I see it now. Thanks.

**Comment by ludolphus** [comment]
haha, your welcome.  no problem :)

**Pull request merged**
